version: "3.8"
services:
  telkom_test_db:
    image: postgres:13.4
    container_name: telkom_test_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telkom_test